### ISSUE TITLE
Example Weseliada Questions

### ISSUE THREAD

**Issue by feud1995** [rafal-c/Weseliada#2]
Can you send us the examples that you have tried the application

**Comment by rafal-c** [comment]
If you mean sample questions, they are in the json file under `resources/data/questions.json` but I actually took those from https://www.familyfeudquestions.com
This is all stated in the README file, so please read if before opening new issues.

**Comment by feud1995** [comment]
You send your Weseliada application in .exe format to my email at ilmisan1995@gmail.com
